baseURL = 'https://example.org/'
locale = 'en-us'
title = "Mad God's Overhaul for Skyrim VR"
theme = 'relearn'
[params]
  themeVariant = 'zen-dark'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false